version: '3'
services:
  ldap:
    build: ./mock-ldap
    ports:
        - "1636:636"
        - "1389:389"
  mail:
    image: rnwood/smtp4dev
    ports:
      - "3000:80"
      - "2525:25"
      - "1143:143"

  app:
    build: .
    environment:
      - LDAP_URL=ldap://ldap:389
    depends_on:
      - ldap
    ports:
      - '8080:8080'
