version: '3'
services:
  ldap:
    image: jenkinsciinfra/mock-ldap:latest
    ports:
        - "1636:636"
        - "1389:389"

  app:
    build: .
    image: accountapp:latest
    environment:
      - JIRA_USERNAME
      - JIRA_PASSWORD
      - JIRA_URL=https://issues.jenkins.io
      - LDAP_URL=ldap://ldap:389
    depends_on:
      - ldap
    ports:
      - '8080:8080'
